### ISSUE TITLE
Exercice2 - RG1

### ISSUE THREAD

**Issue by Alexis-Petit** [bflorat/tp1-miage-2020#2]
Bonjour,

La règle de gestion définie dans le fichier domain.TodoItem n'est pas implémentée dans l'exercice 2. 
Devons nous modifier le code de façon à afficher [LATE] lorsque c'est nécessaire ? 

En vous remerciant.

**Comment by bflorat** [comment]
Exact, j'ai corrigé sur master. Merci pour ce retour.

Ne pas hésiter à proposer une correction par vous-même, cela est un bon exercice que de se demander qui utilise la RG.

Pour la réalisation d'un TU, cela ne change rien car la RG est implémentée (correctement) dans `TodoItem`. C'est une autre classe qui va utiliser la RG et le TU ne teste qu'une classe à la fois...
